apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-exporter-auth
data:
  clouds.yaml: |-
    clouds:
      default:
        auth:
          auth_url: http://keystone.openstack.svc.cluster.local:80/v3
          username: admin
          password: HCloud12#$
          project_domain_name: default
          user_domain_name: default
          project_name: admin
        identity_api_version: 3
        verify: false  
